version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: gpbikes-db
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: gpbikes-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/${MARIADB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MARIADB_USER}
      - SPRING_DATASOURCE_PASSWORD=${MARIADB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - MODS_IMAGES_DIRECTORY=/data/home-images
      - MODS_FILES_DIRECTORY=/data/mods-files
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    volumes:
      - ${NAS_HOME_IMAGES_PATH}:/data/home-images
      - ${NAS_MODS_FILES_PATH}:/data/mods-files

    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: gpbikes-frontend
    ports:
      - "4200:80"
    volumes:
      - ${NAS_HOME_IMAGES_PATH}:/usr/share/nginx/html/home:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mariadb_data:
