version: '3.8'

services:

  backend:
    image: ${BACKEND_IMAGE}
    pull_policy: never
    container_name: gpbikes-backend
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - MODS_IMAGES_DIRECTORY=/data/home-images
      - MODS_FILES_DIRECTORY=/data/mods-files
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    volumes:
      - ${NAS_HOME_IMAGES_PATH}:/data/home-images
      - ${NAS_MODS_FILES_PATH}:/data/mods-files
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE}
    pull_policy: never
    container_name: gpbikes-frontend
    ports:
      - "4200:80"
    volumes:
      - ${NAS_HOME_IMAGES_PATH}:/usr/share/nginx/html/home:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mariadb_data:
